# Generated by Django 4.1.1 on 2023-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrax23', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_worth',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
