# Generated by Django 4.1.4 on 2023-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrax23', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=100)),
                ('image', models.ImageField(default='astrax23/images/team_images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(default='astrax23/images/sponsor_images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
