# Generated by Django 4.0.5 on 2023-02-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrax23', '0002_event_price_worth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='insta_link',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='linkedin_link',
            new_name='insta',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Position_of_head',
            new_name='position',
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(default='https://www.youtube.com/watch?v=33Xe3z8L73A'),
        ),
    ]
