# Generated by Django 4.1.4 on 2023-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrax23', '0002_team_alter_sponsor_image_alter_sponsor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='astrax23/images/events_images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
