# Generated by Django 4.1.4 on 2023-02-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrax23', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designation',
            new_name='Position_of_head',
        ),
        migrations.RemoveField(
            model_name='team',
            name='relationship_status',
        ),
        migrations.AddField(
            model_name='team',
            name='insta_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=33Xe3z8L73A'),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=33Xe3z8L73A'),
        ),
    ]
